# Generated by Django 2.1.7 on 2019-04-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boimelaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='stalls',
            name='stall_id',
        ),
    ]
