# Generated by Django 2.1.7 on 2019-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boimelaApp', '0004_auto_20190406_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('book_name',)},
        ),
        migrations.AlterModelOptions(
            name='stall',
            options={'ordering': ('stall_name',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='book_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('SF', 'SCI-FI'), ('AC', 'ACTION'), ('HR', 'HORROR'), ('RM', 'ROMANTIC')], default='Type N/A', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='stalls',
            field=models.ManyToManyField(to='boimelaApp.Stall'),
        ),
        migrations.AddField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('BK', 'Freshman'), ('FD', 'Food')], default='Type N/A', max_length=2),
        ),
    ]
