# Generated by Django 2.1.7 on 2019-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boimelaApp', '0005_auto_20190408_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('BK', 'Book'), ('FD', 'Food')], default='Type N/A', max_length=2),
        ),
    ]
