# Generated by Django 2.2 on 2019-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boimelaApp', '0007_auto_20190413_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Food', 'Food')], default='Type N/A', max_length=10),
        ),
    ]
