# Generated by Django 2.2 on 2019-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boimelaApp', '0008_auto_20190413_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('SCIFI', 'SCI-FI'), ('ACTION', 'ACTION'), ('HORROR', 'HORROR'), ('ROMANTIC', 'ROMANTIC')], default='Type N/A', max_length=10),
        ),
    ]
